module.exports = {
  uz: {
    heroTitle: "Mazali ta'mlar vaqti — har kuni <em>o'z vaqtida</em>.",
    heroSubtitle: "ObedTime — ofislar, korxonalar va tadbirlar uchun issiq tushlik yetkazib berish hamda ketering xizmati.",
    aboutTitle: "Ish vaqtingizni tushlik tashvishisiz o'tkazing",
    aboutText: "ObedTime — Toshkentdagi ofislar va kompaniyalar uchun kundalik issiq tushlik yetkazib beruvchi ketering xizmati.",
    stat1num: "400+", stat1cap: "kundalik buyurtma",
    stat2num: "100%", stat2cap: "yangi va halol mahsulotlar",
    stat3num: "12:00–13:00", stat3cap: "yetkazib berish vaqti",
    servicesTitle: "Nima taklif qilamiz",
    servicesSubtitle: "Ofis uchun kundalik tushlikdan tortib aniq vaqtda yetkazib berishgacha.",
    s1title: "Ofis uchun tushlik", s1text: "Har kuni belgilangan vaqtda ofisingizga issiq tushlik yetkazib beramiz.",
    s2title: "Yetkazib berish", s2text: "Shahar bo'ylab belgilangan vaqt oralig'ida aniq va tez yetkazib berish xizmati.",
    s3title: "Individual menyu", s3text: "Ovqatlanish afzalliklari va allergiyalarni hisobga olgan holda menyuni moslashtiramiz.",
    menuTitle: "Kunlik menyudan namunalar",
    menuSubtitle: "Narxlar va taomlar haftalik menyuga qarab o'zgarishi mumkin.",
    scheduleTitle: "Har kuni aniq vaqtda",
    sched1label: "Buyurtmalar qabul qilinadi", sched1time: "9:00 – 11:00", sched1text: "Ertalab shu oraliqda buyurtmalaringizni qabul qilamiz.",
    sched2label: "Yetkazib berish", sched2time: "12:00 – 13:00", sched2text: "Tushlik shu vaqt oralig'ida ofisingizga yetkaziladi.",
    contactTitle: "So'rov qoldiring",
    contactText: "Ismingiz va telefon raqamingizni qoldiring — 30 daqiqa ichida siz bilan bog'lanamiz.",
    infoPhone: "+998 95 141 55 55", infoEmail: "info@obedtime.uz",
    infoAddress: "Toshkent sh., Chilonzor tumani, Oq tepa (ObedTime)",
    infoHours: "Har kuni soat 9:00 dan 11:00 gacha",
    infoPhone2: "+998 95 141 55 55"
  },
  ru: {
    heroTitle: "Время вкусных обедов — каждый день <em>вовремя</em>.",
    heroSubtitle: "ObedTime — доставка горячих обедов и кейтеринг для офисов, компаний и мероприятий.",
    aboutTitle: "Проводите рабочее время без забот об обеде",
    aboutText: "ObedTime — служба кейтеринга в Ташкенте, которая ежедневно доставляет горячие обеды в офисы и компании.",
    stat1num: "400+", stat1cap: "заказов в день",
    stat2num: "100%", stat2cap: "свежие и халяльные продукты",
    stat3num: "12:00–13:00", stat3cap: "время доставки",
    servicesTitle: "Что мы предлагаем",
    servicesSubtitle: "От ежедневных обедов для офиса до доставки точно по времени.",
    s1title: "Обеды для офиса", s1text: "Каждый день доставляем горячий обед в ваш офис точно в назначенное время.",
    s2title: "Доставка", s2text: "Точная и быстрая доставка по городу в установленное время.",
    s3title: "Индивидуальное меню", s3text: "Подбираем меню с учётом предпочтений и аллергий.",
    menuTitle: "Примеры блюд дня",
    menuSubtitle: "Цены и блюда могут меняться в зависимости от недельного меню.",
    scheduleTitle: "Каждый день точно по времени",
    sched1label: "Приём заказов", sched1time: "9:00 – 11:00", sched1text: "Принимаем ваши заказы утром в этом промежутке времени.",
    sched2label: "Доставка", sched2time: "12:00 – 13:00", sched2text: "Обед доставляется в ваш офис в это время.",
    contactTitle: "Оставьте заявку",
    contactText: "Оставьте имя и номер телефона — свяжемся с вами в течение 30 минут.",
    infoPhone: "+998 95 141 55 55", infoEmail: "info@obedtime.uz",
    infoAddress: "г. Ташкент, Чиланзарский р-н, Ок-тепа (ObedTime)",
    infoHours: "Ежедневно с 9:00 до 11:00",
    infoPhone2: "+998 95 141 55 55"
  }
};
